### ISSUE TITLE
AWS Lambda <-> Hexagonal pattern query

### ISSUE THREAD

**Issue by 0v3rst33r** [tarasowski/hexagonal-architecture-lambda#2]
@tarasowski This is not an issue, but rather a shout-out to touch base about the structure of your `AWS Lambda <-> Hexagonal` pattern.

I am curious about your thought process regarding having the Lambda's handler inside a `primary adapter (hexagonal-architecture-lambda/adapter-api.js)` and calling it `API`.

I have been using the `Hexagonal` pattern quite successfully in a `NodeJS microservices` setup for more than 2 years now, but am now transitioning to `serverless (AWS)` but still want to use the `Hexagonal` pattern, and thus I stumbled onto your repository.

I do see you have not committed/pushed to this repository in quite a while and is this something that you are still using the way it is here now, or has it evolved?

My situation is:
```
AWS API Gateway -> AWS Lambda -> AWS Aurora Serverless
```
but down the line I will be invoking the lambda from other AWS services as well (e.g. SNS as I need to get data stored in Aurora from other event sources as well), and for this reason my lambda will be executed from different contexts (adapters if you will?), and thus I can not wrap my lambda's _handler function_ in a `Primary Adapter - REST API`.

I see the `Primary Adapter` being AWS Lambda's invoker itself, and the execution context of the lambda (where I reference the handler function itself) is then the `application layer` already as oppose to `infrastructure` layer.

As I typed that now I realised that may not be entirely true as you have _user-flow & business related_ code in your `application layer` so I can not specify the `lambda handler` in the `application layer` at all, otherwise I break the `Hexagonal` pattern.

I hope my rantings are making sense.

Hope to hear from you,
Regards

**Comment by tarasowski** [comment]
Hey,

even in your case if you want to invoke the lambda from different sources, I would simply create a router for the ports before the adapter. But to come back to your first question, indeed I moved from hexagonal architecture away. There is a much simpler approach that is a pipeline of functions. You can see an example here:

```py

pipeline = init(
        input_=sns_reader,
        filters=[
                unpack_ip,
                unpack_ua,
                ua_lookup,
                ip_lookup,
                merge_to_dict,
                json_decode,
                add_status,
                ],
        output=s3_writer,
        error=s3_failed
        )

def handler(event: dict, ctx=None) -> ():
    return pipeline(event)
```
https://github.com/pipes/google-analytics-to-s3/blob/tarasowski/campaign-data/functions/enrichment/main.py

or this one in js

```js
const pipeline = pipe([
   // encase :: DefaultValue -> (a -> b) -> DefaultValue || b
      encase ("San Francisco") (x => x.cities[5]),
   // map :: (a -> b) -> a -> b
      map (x => x.toUpperCase()),
   // encase :: DefaultValue -> (a -> b) -> DefaultValue || b
      encase ("B") (str => str.charAt(0)),
   // recover :: DefaultValue -> a -> DefaultValue || a
      recover ("Nothing")
    ]) (user),
```
https://github.com/tarasowski/basefp

What I do now is, if a function is a pure function, means no side-effects I do test it via a unit test. If the function has side-effects (e.g. calling the db) I do integration tests, so no mocks! I do just try to hit the real db (development). Checkout this post, it explains very well the concept: https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a

**Comment by 0v3rst33r** [comment]
Thank you for your answer, appreciated!

I agree with the no mocking if it can be avoided (also avoids sitting with unit **and** integration test suites).

For the most part I do not have to stay too nimble as there is quite a bit of business logic with some of my implementations, with which the _Hexagonal Pattern + DDD_ combo is very handy.

Thanks again for replying,
Regards
